<form id="ML_form" data-href="/<?= $this->module ?>/ajaxMailingList/add">
  <div id="mailingList" class="modulePadding">
    <label for="ML_email" class="label fl">Email</label>
    <input type="email" id="ML_email" class="email input" autocomplete="on" autofocus="autofocus" placeholder="Type your email here" required="required" />

    <span id="ML_info" class="fl">&nbsp;&nbsp;</span>
    <div class="clearBoth"></div>

    <input id="ML_emailAdd" type="submit" class="button fr" value="Send" />
    <div class="clearBoth"></div>
  </div>
</form>
<?php self::js(CMS_JS_PATH . 'mailingList'); ?>
