<?
echo '<div class="' . (2 == $type ? '' : 'moduleStyle1 ') . 'moduleType' . $type . '">';

  $hztl = false;
  if(1 == $type)
    echo '<nav class="menuv">';
  else if(2 == $type)
  {
    echo '<nav class="menuh center">';
    $hztl = true;
  }

  foreach($module as $moduleName => $moduleItems)
  {
    if(!$hztl)
    { ?>
      <ul class="nodecoration shadowEffect">
        <li class="menusVHeaderUl menusVHeaderLi">
          <?= $moduleName ?>
        </li><?
    }

    switch($type)
    {
      case 0:
        $connCenter = false;
        require CMS_VIEWS_PATH . 'connection.phtml';
        break;

      case 1:
        $cptMenuItems = count($moduleItems) - 1;
        foreach($moduleItems as $key => $menuItem)
        {
          if('' != $menuItem['em_contenu'])
          {
            ?><li class="<? if($key == $cptMenuItems){ echo 'menuVPad ';}?>menuVLi">
              <a href="#" class="menuVLink" data-tooltip="<?= $menuItem['titre'] ?>"><?= $menuItem['em_contenu'] ?></a>
            <?
          }
        }
        ?></ul><?
        break;

      case 2:
      if(2 == $moduleItems[0]['id']) // TODO à gérer autrement
        break;
        ?><ul class="menusHUl nodecoration"><?
        foreach($moduleItems as $menuItem)
        {
          if('' != $menuItem['em_contenu'])
          {?>
            <li class="menuHLi" data-href="/<?= 'article/show/' , $menuItem['a_contenu'] ?>" data-tooltip="<?= $menuItem['titre'] ?>">
              <?= $menuItem['em_contenu'] ?>
          <?}
        }
        ?>
        </li>
        <div id="lightsContainer">
          <div id="lightsRelativeContainer">
            <div id="light1" class="light"></div>
            <div id="light2" class="light"></div>
            <div id="light3" class="light"></div>
          </div>
        </div>
        </ul><?
        break;

      case 4:
        require CMS_VIEWS_PATH . 'mailingList.phtml';
        break;
    }
  }

  if(1 == $type)
    echo '</nav>';

  echo '</div>'; ?>
