<?
echo '<div class="' . (2 == $type ? '' : 'module-style1 ') . 'module-type' . $type . '">';

  $hztl = false;
  if(1 == $type)
    echo '<nav class="menu-v" role="navigation">';
  else if(2 == $type)
  {
    echo '<nav class="menu-h center" role="navigation">';
    $hztl = true;
  }

  foreach($module as $moduleName => $moduleItems)
  {
    if(!$hztl)
    { ?>
      <ul class="no-decoration shadow-effect">
        <li class="menus-v-header-ul menus-v-header-li">
          <?= $moduleName ?>
        </li><?
    }

    switch($type)
    {
      case 0:
        $connCenter = false;
        require CMS_VIEWS_PATH . 'connection.phtml';
        break;

      case 1:
        $cptMenuItems = count($moduleItems) - 1;
        foreach($moduleItems as $key => $menuItem)
        {
          if('' != $menuItem['em_contenu'])
          {
            ?><li class="<? if($key == $cptMenuItems){ echo 'menu-v-pad ';}?>menu-v-li">
              <a href="#" class="menu-v-link" data-tooltip="<?= $menuItem['titre'] ?>"><?= $menuItem['em_contenu'] ?></a>
            <?
          }
        }
        ?></ul><?
        break;

      case 2:
      if(2 == $moduleItems[0]['id']) // TODO à gérer autrement
        break;
        ?><ul class="menus-h-ul no-decoration"><?
        foreach($moduleItems as $menuItem)
        {
          if('' != $menuItem['em_contenu'])
          {?>
            <li class="menu-h-li" data-href="/<?= 'article/show/' , $menuItem['a_contenu'] ?>" data-tooltip="<?= $menuItem['titre'] ?>">
              <?= $menuItem['em_contenu'] ?>
          <?}
        }
        ?>
        </li>
        <div id="lights-container">
          <div id="lights-relative-container">
            <div class="light light1"></div>
            <div class="light light2"></div>
            <div class="light light3"></div>
          </div>
        </div>
        </ul><?
        break;

      case 4:
        require CMS_VIEWS_PATH . 'mailingList.phtml';
        break;
    }
  }

  if(1 == $type)
    echo '</nav>';

  echo '</div>'; ?>
