<?php
declare(strict_types=1);
namespace otra\src\views\debugBar\sql;

use const otra\cache\php\CORE_VIEWS_PATH;
use function otra\cache\php\{block, endblock};
use function otra\tools\trans;

require CORE_VIEWS_PATH . 'profiler/layout.phtml';

block('title', 'Profiler — SQL');
block('view');
/** @var string $sqlLogs */
?>
<div id="sql-container">
  <div class="sql-buttons">
    <button type="button" id="profiler--clear-sql-logs" class="ripple sql-buttons--item"><?= trans('Clear SQL logs') ?></button>
    <button type="button" id="profiler--refresh-sql-logs" class="ripple sql-buttons--item"><?= trans('Refresh SQL logs') ?></button>
  </div>
  <div id="profiler--sql--logs" class="profiler--sql--logs"><?= $sqlLogs ?></div>
</div>
<?php
endblock();
