<form>
	<table class="fl">
		<thead id="usersHeader">
			<tr>
				<th><input id="all" type="checkbox" data-tooltip="Select/Deselect All" /></th>
				<th>Email</th>
				<th>Password</th>
				<th>Pseudo</th>
				<th>Role</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody id="usersBody">
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<? foreach($users as $user) {?>
			<tr id="<?= $user['id_user'] ?>">
				<td><input type="checkbox"/></td>
				<td class="mail"><?= $user['mail'] ?></td>
				<td><?= $user['pwd'] ?></td>
				<td><?= $user['pseudo'] ?></td>
				<td data-value="<?= $user['id_role'] ?>"><?= $user['nom'] ?></td>
				<td>
					<span class="softBtn" data-tooltip="Makes the line editable"><a class="rightPad edit">Edit</a></span>
					<span class="softBtn" data-tooltip="Delete the user"><a class="fontBtn delete">-</a></span>
				</td>
			</tr>
			<? } ?>
			<tr id="trOptions">
				<td colspan="6" class="options">
					<span id="addBtn" class="softBtn smallBtn" data-tooltip="Add a new user"><a class="fontBtn rightPad">+</a></span>
					<span id="delAllBtn" class="softBtn smallBtn" data-tooltip="Delete all the selected users !"><a id="deleteAll" class="fontBtn rightPad">-</a></span>
					<span id="valAllBtn" class="softBtn smallBtn" data-tooltip="Validate all the selected users !"><a id="validateAll" class="fontBtn rightPad">V</a></span>
				</tr>
				<tr>
					<td class="final" colspan="6"></td>
				</tr>

			</tbody>
		</table>
	</form>
</div>
<?
if(!in_array('users', $_SESSION['js'])) {
	// dump($this->viewJSPath . 'users');
	// self::js($this->viewJSPath . 'users');
	// self::css(CMS_CSS_PATH . 'users');
	$_SESSION['js'][] = 'users';
	$_SESSION['css'][] = 'users';
	echo '<script> window.roles = ' . json_encode($roles) . ';</script>';
}
