<thead>
  <tr>
    <th>
      <input id="modules-all" class="_select-all no-label" type="checkbox">
      <label for="modules-all"></label>
    </th>
    <th><?= t('Content') ?></th>
    <th><?= t('Detail') ?></th>
    <th><?= t('Parent') ?></th>
    <th><?= t('Order') ?></th>
    <th><?= t('Right') ?></th>
  </tr>
</thead>
<tbody id="tbody">
  <? if(!empty($items)) {
      foreach($items as $item)
      {?>
      <tr>
        <td>
          <input type="checkbox" id="article_<?= $item['id'] ?>" class="no-label"><!-- change THAT WITH A CORRECT ID !!! -->
          <label for="article_<?= $item['id'] ?>"></label><!-- SAME HERE -->
        </td>
        <td><?= $item['contenu'] ?></td>
        <td><a class="soft-btn see-elements" data-id="<?= $item['id'] ?>"><?= t('Voir les éléments associés') ?></a>
        <td><?= $item['parent'] ?></td>
        <td><?= $item['order'] ?></td>
        <td><?= $right[$item['droit']] ?></td>
      </tr>
  <? } } ?>
</tbody>
