<div id="modules">
  <div class="breadCrumb"><a>Modules</a> >> Elements</div>

  <input type="search" id="moduleSearch" placeholder="<? t('Search by module') ?>" class="input">
  <input type="search" id="elementSearch" placeholder="<? t('Search by element') ?>" class="input">
  <input type="search" id="articleSearch" placeholder="<? t('Search by article') ?>" class="input">
  <div class="clearBoth"></div><br>

  <table id="table0">
    <thead>
      <tr>
        <th><?= t('Détail') ?></th>
        <th><?= t('Parent') ?></th>
        <th><?= t('Order') ?></th>
        <th><?= t('Right') ?></th>
        <th><?= t('Content') ?></th>
      </tr>
    </thead>
    <tbody>
      <? if(!empty($items)) {
          foreach($items as $item)
          {?>
          <tr>
            <td><a class="softBtn seeElements" data-id="<?= $item['id_elementsmenu'] ?>"><?= t('Voir les éléments associés') ?></a>
            <td><?= $item['parent'] ?></td>
            <td><?= $item['ordre'] ?></td>
            <td><?= $right[$item['droit']] ?></td>
            <td><?= $item['contenu'] ?></td>
          </tr>
          <? } } ?>
    </tbody>
  </table>
  </div>
  </td>
</div>
