<thead>
  <tr>
    <th><?= t('Parent') ?></th>
    <th><?= t('Détail') ?></th>
    <th><?= t('Order') ?></th>
    <th><?= t('Right') ?></th>
    <th><?= t('Content') ?></th>
  </tr>
</thead>
<tbody id="tbody">
  <? if(!empty($items)) {
      foreach($items as $item)
      {?>
      <tr>
        <td><? if (-1 != $item['parent']) {?> <a class="softBtn seeElements" data-id="<?= $item['id_elementsmenu'] ?>"><?= t('See parent module'); ?></a><? } else {?>No parent module.<? } ?>
        <td><? if (0 != $item['aEnfants']) {?><a class="softBtn seeElements" data-id="<?= $item['id_elementsmenu'] ?>"><?= t('See articles') ?></a>
        <td><?= $item['ordre'] ?></td>
        <td><?= $right[$item['droit']] ?></td>
        <td><?= $item['contenu'] ?></td>
      </tr>
      <? } } ?>
</tbody>
