<thead>
  <tr>
    <th><?= t('Détail') ?></th>
    <th><?= t('Type') ?></th>
    <th><?= t('Position') ?></th>
    <th><?= t('Order') ?></th>
    <th><?= t('Right') ?></th>
    <th><?= t('Content') ?></th>
  </tr>
</thead>

<tbody>
  <?
if(!empty($items)) {
  foreach($items as $item)
{?>
<tr>
  <td><a class="softBtn lightBtn seeElements" data-id="<?= $item['id'] ?>"><?= t('Voir les éléments associés') ?></a>
  <td><?= $moduleTypes[$item['type']] ?></td>
  <td><?= $item['position'] ?></td>
  <td><?= $item['ordre'] ?></td>
  <td><?= $right[$item['droit']] ?></td>
  <td><?= $item['contenu'] ?></td>
</tr>
<? } } ?>
</tbody>
