<tab-content id="tab0" class="active-tab">
  <nav>
    <ul id="module-tabs" class="menus module-0__menus" role="tablist">
      <li id="modules-mgt" class="tab active-tab center" role="presentation" data-tooltip="Modules management" data-href="/backend/ajax/modules/search/module?search=" data-fn="replaceModulesContent"><?= t('Modules'); ?>
      <li id="elements-mgt" class="tab center" role="presentation" data-tooltip="Elements management" data-href="/backend/ajax/modules/search/element?search=" data-fn="replaceElementsContent"><?= t('Elements'); ?>
      <li id="articles-mgt" class="tab center" role="presentation" data-tooltip="Articles Management" data-href="/backend/ajax/modules/search/article?search=" data-fn="replaceArticlesContent"><?= t('Articles'); ?>
    </ul>
  </nav>
	<input type="search" id="module-search" role="search" placeholder="<?= t('Search by module') ?>" class="input _generic-search" data-href="/backend/ajax/modules/search/module" data-fn="replaceModulesContent">
	<input type="search" id="element-search" role="search" placeholder="<?= t('Search by element') ?>" class="input _generic-search" data-href="/backend/ajax/modules/search/element" data-fn="replaceElementsContent">
	<input type="search" id="article-search" role="search" placeholder="<?= t('Search by article') ?>" class="input _generic-search" data-href="/backend/ajax/modules/search/article" data-fn="replaceArticlesContent">
	<div class="clear-both"></div><br>

	<table id="table0" role="tabpanel">
			<? require __DIR__ . '/modulesPartial.phtml'; ?>
	</table>
</tab-content>
