<tabContent id="tab0">
	<div id="breadCrumb">Modules</div>

	<input type="search" id="moduleSearch" placeholder="<? t('Search by module') ?>" class="input _genericSearch" data-href="/backend/ajax/modules/search/module" data-fn="replaceModulesContent">
	<input type="search" id="elementSearch" placeholder="<? t('Search by element') ?>" class="input _genericSearch" data-href="/backend/ajax/modules/search/element" data-fn="replaceElementsContent">
	<input type="search" id="articleSearch" placeholder="<? t('Search by article') ?>" class="input _genericSearch" data-href="/backend/ajax/modules/search/article" data-fn="replaceArticlesContent">
	<div class="clearBoth"></div><br>

	<table id="table0">
			<? require 'modulesPartial.phtml'; ?>
	</table>
	</div>
</tabContent>
