<thead>
  <tr>
    <th>
      <input id="modules-all" class="_select-all no-label" type="checkbox">
      <label for="modules-all"></label>
    </th>
    <th><?= t('Content') ?></th>
    <th><?= t('Type') ?></th>
    <th><?= t('Position') ?></th>
    <th><?= t('Order') ?></th>
    <th><?= t('Right') ?></th>
    <th><?= t('Action') ?></th>
  </tr>
</thead>

<tbody>
  <?
if(!empty($items)) {
  foreach($items as $item)
{?>
<tr>
  <td>
    <input type="checkbox" id="module-<?= $item['id'] ?>" class="no-label"><!-- change THAT WITH A CORRECT ID !!! -->
    <label for="module-<?= $item['id'] ?>"></label><!-- SAME HERE -->
  </td>
  <td><?= $item['contenu'] ?></td>
  <td><?= $moduleTypes[$item['type']] ?></td>
  <td><?= $item['position'] ?></td>
  <td><?= $item['ordre'] ?></td>
  <td><?= $right[$item['droit']] ?></td>
  <td><a class="soft-btn circle-border see-details" data-id="<?= $item['id'] ?>" title="<?= t('See elements') ?>"></a>
</tr>
<? } } ?>
</tbody>
