<? self::css(CORE_CSS_PATH . 'debug_bar'); ?>
<div id="dbgBar">
   <? echo '\'', $this->route, '\' | ', $this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s | <span class="<?= (isset($_SESSION['sid'])) ? 'dbg_on' : 'dbg_off'?>">Connected</span>
   | <a id="showSQL" class="dbgBtn">Inspecter SQL</a>
   <p id="toggle">▶</p>
</div><div id="dbgBarXS">
	<p id="toggleSmall">▼</p>
</div>
<?php self::js(array(CORE_JS_PATH . 'debugBar')); ?>
