<?php self::css(CORE_CSS_PATH . 'debug_bar'); ?>
<div id="debugBar">
  <span class="<?= ($cache) ? 'dbg_on' : 'dbg_off'; ?>">Cache </span>
  was<span class="<?= (self::$cache_used) ? 'dbg_on' : 'dbg_off' ?>"> used</span>
   | <?php echo '\'', $this->route, '\' | ',$this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s | <span class="<?= (isset($_SESSION['sid'])) ? 'dbg_on' : 'dbg_off'?>">Connected</span>
   <p id="toggle" class="toggle deactivate"></p>
</div><div id="debugBarSmall">
	<p id="toggleSmall" class="toggle activate"></p>
</div>
<?php self::js(array(CORE_JS_PATH . 'debugBar')); ?>
