<?
self::layout();
self::title('Exception !');
self::css(array(CORE_CSS_PATH . 'lionel_exception'));
?>
<div id="exception" class="textCenter">Exception</div>
<div id="explications" class="textCenter correctDisplay"><?
  if (isset($code)) echo 'Error code ' , $code , '. ';
  echo 'Description : \'' , $message , '\' in ' , $file , ' at line ' , $line, '<br />'; ?>
	<br />
	<table class="radius">
		<thead>
	  	<tr class="head">
	  		<th>Error Code</th>
			<th>Function</th>
			<th>Line</th>
			<th>File</th>
			<th>Arguments</th>
		</tr>
	</thead>
	<tbody>
	  <? for($i=0, $trace = $backtraces, $max = count($trace); $i < $max; $i += 1)
	  {
	  	$now = $trace[$i];
	//         $args = $now['args'];
	  	?><tr>
	  		<td></td>
	  	 	<td>
				<?= (isset($now['function'])) ? $now['function']
		                                      : '-' ?>
			</td>
			<td><?=
		        (isset($now['line'])) ? $now['line']
		                              : '-' ?>
			</td>
			<td>
				<?= (isset($now['file'])) ? $now['file']
		                                  : '-' ?>
			</td>
			<td>
				<i class="showArgs">Show</i>
			</td>
		</tr>
		<tr class="deepContent">
			<td colspan="0"><? if(0 == $i) unset($now['args']['variables']);
			 convertArrayToShowable($now['args'], 'Arguments', 'variables'); echo $now['args']; ?></td>
		</tr>
		<?
	  }?>
	  </tbody>
	</table>
	<br />
	<?= $context ?>
</div>
<? self::js(array(CORE_JS_PATH . 'tools')); ?>
