<!DOCTYPE html>
<!-- <meta http-equiv="X-UA-Compatible" content="IE=8"/> -->
<meta name="viewport" content="width=device-width" />
<title> Welcome to the LP Framework !</title>
<? self::favicon('favicon.png', 'favicon.ico'); ?>
<!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
<!--[if IE 7 ]> <html class="ie7"> <![endif]-->
<!--[if IE 8 ]> <html class="ie8"> <![endif]-->
<!--[if IE 9 ]> <html class="ie9"> <![endif]-->
<!--[if IE 10 ]> <html class="ie10"> <![endif]-->
<!--[if (gt IE 10)|!(IE)]><!--> <html> <!--<![endif]-->
<body>coucou</body>
