<?
self::layout();
self::title('Welcome to the LPCMS !');
self::css(array(CMS_CSS_PATH . 'generic', CMS_CSS_PATH . 'main', CMS_CSS_PATH . 'form'));
self::js(array('' => 'http://code.jquery.com/jquery-1.10.1.min', CMS_JS_PATH . 'main'), true);
?>
<div id="backgroundspe"></div>
<div id="mainFrame">
<? require CMS_VIEWS_PATH . 'header.phtml'; ?>
  <div id="bgMiddle">

    <div class="moduleStyle1">
      <ul class="menusVHeaderUl nodecoration">
        <li class="menusVHeaderLi tcenter">
          Connexion
      </ul>
      <? $connCenter = true;require CMS_VIEWS_PATH . 'connection.phtml'; ?>
      <div class="clearBoth"></div>
      </div>
    </div>

  <?  require CMS_VIEWS_PATH . 'footer.phtml';  ?>
  </div>
</div>
