<ul id="menus">
	<li class="tab <? if ('Modules' == $menu) echo 'activeTab '; ?>tcenter" data-tooltip="Modules management" data-href="/backend/modules">Modules
	<li class="tab <? if ('General' == $menu) echo 'activeTab '; ?>tcenter" data-tooltip="General options management" data-href="/backend/general">General options
	<li class="tab <? if ('Stats' == $menu) echo 'activeTab '; ?>tcenter" data-tooltip="Statistics management" data-href="/backend/stats">Stats
	<li class="tab <? if ('Users' == $menu) echo 'activeTab '; ?> tcenter" data-tooltip="Users management" data-href="/backend/users">Users</ul>

<div id="content"><? require __DIR__ . '/../ajax' . $menu .'/index.phtml'; ?>
