<?php
declare(strict_types=1);
namespace otra\src\views\profiler\templateStructure;

use const otra\cache\php\CORE_VIEWS_PATH;
use function otra\cache\php\{block, endblock};

/**
 * @var bool         $cacheEnabled
 * @var false|string $templateVisualization
 */
require CORE_VIEWS_PATH . 'profiler/layout.phtml';
block('title', 'Profiler - Template structure');
block('view');

if ($templateVisualization !== false)
  echo base64_decode($templateVisualization);
else
{
?><p class="no-template-in-session">There is no template data in the session right now.</p><?php
}
endblock();
