<?php
declare(strict_types=1);
require CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<html>
<head>
  <title>
    <?php
    $title = 'Starter template homepage';
    block('title');
    echo $title;
    endblock();
    ?>
  </title>

  <meta property="og:site_name" content="<?= $title ?>">
  <?php block('preThings', '') ?>
</head>

<body>
<?php block('body'); ?>
Hello!
<?php endblock(); ?>
</body>

<?php
block('title', 'Hello world starter template');
block('body');
parent(); ?><br/>
  It's the basic template.
<?php
block('preThings');
echo '<monerreur></monerreur>';
endblock();
?>
<?php endblock();
