<?php require CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<html lang="en">
<title>
  <?php block('title'); ?>
  Welcome to OTRA!
  <?php endblock(); ?>
</title>

<body>
<?php block('body'); ?>
  Hello!
  <?php block('test'); ?>
    exact
    <?php block('body'); ?>
      test
    <?php endblock(); ?>
    exact 2
  <?php endblock(); ?>
  Hello!End
<?php endblock(); ?>
</body>
<?php
block('title', 'Welcome to the OTRA!');
block('body');
?>
  Hello World!
  <?php parent();?>
  Hello World!after<?php
endblock();
