<?php
declare(strict_types=1);

use function cache\php\{block, endblock, parent};
use const otra\cache\php\CORE_PATH;
require CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title><?php
    block('title'); ?>
    Welcome to OTRA!<?php
    endblock(); ?>
  </title>
</head>
<body>
<?php block('body'); ?>
  Hello!
  <?php block('test'); ?>
    exact
  <?php endblock(); ?>
  super
<?php endblock(); ?>
top
</body>
<?php
block('title', 'Welcome to the OTRA!');
block('body');
?>
  Hello World!
<?php
endblock();
?><?php
block('body'); ?>
  test
<?php parent();
endblock(); ?>
