<?php
declare(strict_types=1);
require CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title><?php
    block('title'); ?>
    Welcome to OTRA!<?php
    endblock();
  ?></title>
  <?php block('meta' , ''); ?>
  <meta charset="UTF-8" />
  <?php block('fonts', ''); ?>
</head>
<body>
<?php block('body'); ?>
  Hello!<?php
  block('test'); ?>
    exact<?php
  endblock(); ?>
  super
<?php endblock(); ?>
  top
</body>
<?php
block('title', 'Welcome to the OTRA!');
block('meta'); ?>
<meta http-equiv="Accept" />
<?php endblock();
block('fonts'); ?>
<link rel="prefetch" />
<?php
endblock();
block('body');
?>
  Hello World!
<?php
endblock();
?><?php
block('body'); ?>
  test
<?php parent();
endblock(); ?>
