<?php require CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<html lang="en">
<title>
  <?php block('title'); ?>
  Welcome to OTRA!
  <?php endblock(); ?>
</title>

<?php block('meta', ''); ?>
<meta charset="UTF-8" />
<?php block('fonts', ''); ?>

<body>
<?php block('body'); ?>
  Hello!
  <?php block('test'); ?>
    exact
    <?php block('body'); ?>
      test
    <?php endblock(); ?>
    exact 2
  <?php endblock(); ?>
  Hello!End
<?php endblock(); ?>
</body>
<?php
block('title', 'Welcome to the OTRA!');
block('meta'); ?>
<meta http-equiv="Accept" />
<?php endblock();
block('fonts'); ?>
<link rel="prefetch" />
<?php
endblock();
block('body');
?>
  Hello World!
  <?php parent();?>
  Hello World!after<?php
endblock();
