<?php
declare(strict_types=1);

use config\AllConfig;

if (!function_exists('generateArrows'))
{
  /**
   * @param string $inputType
   */
  function generateArrows(string $inputType = 'radio') : void
  {
    $debugBarPosition = isset(AllConfig::$debugConfig) && isset(AllConfig::$debugConfig['barPosition'])
      ? AllConfig::$debugConfig['barPosition']
      : 'top';
    $positions = [
      '▲' => 'top',
      '▶' => 'right',
      '▼' => 'bottom',
      '◀' => 'left'
    ];

    foreach($positions as $arrow => $position)
    {
      if ($inputType === 'radio')
      {
        ?>
        <input type="radio" id="dbg-bar--toggle-<?= $position ?>" name="dbg-bar--position"
               class="dbg-bar--toggle-direction dbg-bar--toggle-<?= $position ?>"<?php
        if ($debugBarPosition === $position)
          echo ' checked';
        ?>>
        <?php
      } else
      {
        ?>
        <label for="dbg-bar--toggle-<?= $position ?>" class="dbg-bar--toggle dbg-bar--toggle-<?= $position ?>"
               title="Move the debug bar to the <?= $position ?>"><?= $arrow ?></label>
        <?php
      }
    }
  }
}
$this::css(CORE_CSS_PATH . 'partials/devMode/devMode'); ?>
<?php generateArrows(); ?>

<div id="dbg-bar" class="dbg-bar">
  <span class="dbg--help-cursor dbg-bar--primary" title="Route">'<?= $this->route ?>'</span>
  <span class="dbg-bar--primary dbg-bar--separator">|</span>
  <span class="otra--help-cursor dbg-bar--primary" title="Bundle"><?= $this->bundle ?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">/</span><!--
  --><span class="otra--help-cursor dbg-bar--primary" title="Module"><?= $this->module ?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">/</span><!--
  --><span class="otra--help-cursor dbg-bar--primary" title="Controller"><?= $this->controller ?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">/</span><!--
  --><span class="otra--help-cursor dbg-bar--primary" title="Action"><?= $this->action ?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">|</span><!--
  --><span class="otra--help-cursor dbg-bar--primary" title="Elapsed time"><?= round(microtime(true) - BEFORE, 3) ?>s</span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">|</span><?php
  if (isset($_SESSION['sid']))
  {
     ?><span class="dbg-bar--logged otra--help-cursor" title="Is a user logged in?">Connected</span><?php
  } else {
    ?><span class="dbg-bar--not-logged otra--help-cursor" title="Is a user logged in?">Disconnected</span><?php
  } ?>
  <span class="dbg--bar--primary dbg-bar--separator">|</span>
  <button id="show-sql" class="dbg-bar--btn">Inspect SQL</button>
  <?php generateArrows('label') ?>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox');
