<?php
declare(strict_types=1);

use config\AllConfig;

if (!function_exists('generateArrows'))
{
  define('OTRA_SLASH_SEPARATOR', '/');

  /**
   * @param string $inputType
   */
  function generateArrows(string $inputType = 'radio') : void
  {
    $debugBarPosition = isset(AllConfig::$debugConfig) && isset(AllConfig::$debugConfig['barPosition'])
      ? AllConfig::$debugConfig['barPosition']
      : 'top';
    $positions = [
      '▲' => 'top',
      '▶' => 'right',
      '▼' => 'bottom',
      '◀' => 'left'
    ];

    foreach($positions as $arrow => $position)
    {
      if ($inputType === 'radio')
      {
        ?>
        <input type="radio" id="dbg-bar--toggle-<?= $position ?>" name="dbg-bar--position"
               class="dbg-bar--toggle-direction dbg-bar--toggle-<?= $position ?>"<?php
        if ($debugBarPosition === $position)
          echo ' checked';
        ?>>
        <?php
      } else
      {
        ?>
        <label for="dbg-bar--toggle-<?= $position ?>" class="dbg-bar--toggle dbg-bar--toggle-<?= $position ?>"
               title="Move the debug bar to the <?= $position ?>"><?= $arrow ?></label>
        <?php
      }
    }
  }

  /**
   * @param string $content
   * @param string $title
   * @param string $separator
   */
  function generateDebugBarPart(string $content, string $title, string $separator = '|') : void
  {
    ?>
    <span class="otra--help-cursor dbg-bar--primary" title="<?= $title ?>"><?= $content ?></span>
    <span class="dbg-bar--primary dbg-bar--separator"><?= $separator ?></span>
    <?php
  }
}
$this::css(CORE_CSS_PATH . 'partials/devMode/devMode'); ?>
<?php generateArrows(); ?>

<div id="dbg-bar" class="dbg-bar">
  <?php
  generateDebugBarPart("'" . $this->route . "'", 'Route');
  generateDebugBarPart($this->bundle, 'Bundle', OTRA_SLASH_SEPARATOR);
  generateDebugBarPart($this->module, 'Module', OTRA_SLASH_SEPARATOR);
  generateDebugBarPart($this->controller, 'Controller', OTRA_SLASH_SEPARATOR);
  generateDebugBarPart($this->action, 'Action');
  generateDebugBarPart(
    round(microtime(true) - BEFORE, 3) . 's',
    'Elapsed time'
  );
  ?>
 <span class="otra--help-cursor dbg-bar--primary" title="Controller">Cache ⓘ</span><!--
  --><span><?= (!isset(AllConfig::$cache) || AllConfig::$cache) ? 'Enabled' : 'Disabled'?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">|</span><!--
  --><span><?= $this::$cacheUsed ?></span><!--
  --><span class="dbg-bar--primary dbg-bar--separator">|</span><?php
  if (isset($_SESSION['sid']))
  {
     ?><span class="dbg-bar--logged otra--help-cursor" title="Is a user logged in?">Connected</span><?php
  } else {
    ?><span class="dbg-bar--not-logged otra--help-cursor" title="Is a user logged in?">Disconnected</span><?php
  } ?>
  <span class="dbg--bar--primary dbg-bar--separator">|</span>
  <button id="show-sql" class="dbg-bar--btn">Inspect SQL</button>
  <?php generateArrows('label') ?>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox');
