<?php
declare(strict_types=1);
namespace otra\src\views\profiler;

use otra\config\Routes;
use function otra\cache\php\{block, endblock};
use const otra\cache\php\CORE_VIEWS_PATH;

/** @var string $route */
require CORE_VIEWS_PATH . 'layout.phtml';
const
  ROUTE_LOGS = 'otra_logs',
  ROUTE_REQUESTS = 'otra_requests',
  ROUTE_ROUTES = 'otra_routes',
  ROUTE_SASS_TREE = 'otra_css',
  ROUTE_TEMPLATE_STRUCTURE = 'otra_templateStructure',
  ROUTE_SQL = 'otra_sql',
  LABEL_CHUNKS = 'chunks',
  ICON = 0,
  LABEL = 1;

define('ANALYZED_PAGE', '?route=' . $_GET['route']);
define('ROUTE', urldecode($_GET['route']));
define('SITE_HOST', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']);

/**
 * Adds an HTML menu item to a list
 *
 * @param string   $routeToTest
 * @param string[] $itemProperties Item label and icon
 */
$menuItem = function (string $routeToTest, array $itemProperties) use ($route)
{
  /** @var string $route */
  ?>
  <li
    class="vertical-menu vertical-menu--container--item<?php
    if ($route === $routeToTest)
      echo ' vertical-menu--container--item-active';
    ?>">
    <a
      href="<?= SITE_HOST . Routes::$allRoutes[$routeToTest][LABEL_CHUNKS][Routes::ROUTES_CHUNKS_URL] . ANALYZED_PAGE ?>"
      rel="noreferrer noopener" class="vertical-menu--container--item--link" >
      <span title="<?= $itemProperties[LABEL] ?>"><?= $itemProperties[ICON] ?> </span>
      <span class="vertical-menu--container--item--link--label"><?= $itemProperties[LABEL] ?></span>
    </a>
  </li>
  <?php
};

block('body');
?>
<h1 class="otra-title">
  OTRA profiler - Data about the route
  <a href="<?= SITE_HOST . Routes::$allRoutes[ROUTE][LABEL_CHUNKS][Routes::ROUTES_CHUNKS_URL] ?>" class="otra-title--link"><?= ROUTE ?></a>
</h1>
<div class="profiler-container flex-container">
  <ul class="vertical-menu vertical-menu--container">
    <?php
    foreach([
      ROUTE_LOGS => ['📄', 'Logs'],
      ROUTE_REQUESTS => ['🔃', 'Request / Response'],
      ROUTE_ROUTES => ['📌', 'Routes'],
      ROUTE_SASS_TREE => ['🖌', 'SASS/SCSS analysis'],
      ROUTE_SQL => ['🗃', 'SQL'],
      ROUTE_TEMPLATE_STRUCTURE => ['📄', 'Template structure']
    ] as $routeToTest => $itemProperties
    )
    {
      $menuItem($routeToTest, $itemProperties);
    }
    ?>
  </ul>
  <?php block('view', ''); ?>
</div>
<?php endblock();
