<?php
declare(strict_types=1);
namespace otra\src\views\profiler;

use otra\config\Routes;
use function otra\cache\php\{block, endblock};
use const otra\cache\php\CORE_VIEWS_PATH;

/** @var string $route */
require CORE_VIEWS_PATH . 'layout.phtml';
const
  ROUTE_SASS_TREE = 'otra_css',
  ROUTE_TEMPLATE_STRUCTURE = 'otra_template_structure',
  ROUTE_SQL = 'otra_sql',
  LABEL_CHUNKS = 'chunks';

define('ANALYZED_PAGE', '?route=' . $_GET['route']);
define('ROUTE', urldecode($_GET['route']));
define('SITE_HOST', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']);

/**
 * Adds an HTML menu item to a list
 *
 * @param string $routeToTest
 * @param string $itemLabel
 */
$menuItem = function (string $routeToTest, string $itemLabel) use ($route)
{
  /** @var string $route */
  ?>
  <li
    class="vertical-menu vertical-menu--container--item<?php
    if ($route === $routeToTest)
      echo ' vertical-menu--container--item-active';
    ?>">
    <a href="<?= SITE_HOST . Routes::$allRoutes[$routeToTest][LABEL_CHUNKS][Routes::ROUTES_CHUNKS_URL] . ANALYZED_PAGE ?>"
       rel="noreferrer noopener"><?= $itemLabel ?></a>
  </li>
  <?php
};

block('body');
?>
<h1 class="otra-title">
  OTRA profiler - Data about the route
  <a href="<?= SITE_HOST . Routes::$allRoutes[ROUTE][LABEL_CHUNKS][Routes::ROUTES_CHUNKS_URL] ?>"><?= ROUTE ?></a>
</h1>
<div class="profiler-container flex-container">
  <ul class="vertical-menu vertical-menu--container">
    <?php
    foreach([
      ROUTE_SASS_TREE => 'SASS/SCSS analysis',
      ROUTE_SQL => 'SQL',
      ROUTE_TEMPLATE_STRUCTURE => 'Template structure'
    ] as $routeToTest => $itemLabel
    )
    {
      $menuItem($routeToTest, $itemLabel);
    }
    ?>
  </ul>
  <?php block('view', ''); ?>
</div>
<?php endblock();
