<div id="profiler" class="profiler">
  <div>
    <button id="profiler--hide-profiler" class="ripple"><?= t('Hide the profiler') ?></button>
    <button id="profiler--clear-sql-logs" class="ripple"><?=t('Clear SQL logs') ?></button>
    <button id="profiler--refresh-sql-logs" class="ripple"><?= t('Refresh SQL logs') ?></button><br><br>
  </div>
  <div id="profiler--sql--logs" class="profiler--sql--logs"><?php
    /** @var string $sqlLogs */
    echo $sqlLogs;
  ?></div>
</div>
