<?php
declare(strict_types=1);

use function otra\tools\trans;
?>
<div id="profiler" class="profiler">
  <div>
    <button id="profiler--hide-profiler" class="ripple"><?= trans('Hide the profiler') ?></button>
    <button id="profiler--clear-sql-logs" class="ripple"><?= trans('Clear SQL logs') ?></button>
    <button id="profiler--refresh-sql-logs" class="ripple"><?= trans('Refresh SQL logs') ?></button><br><br>
  </div>
  <div id="profiler--sql--logs" class="profiler--sql--logs"><?php
    /** @var string $sqlLogs */
    echo $sqlLogs;
  ?></div>
</div>
