<?php
declare(strict_types=1);
namespace otra\src\views\debugBar;
/**
 * @var int $debugBarTabIndexActualValue
 */
$elapsedTime = (int) (round(microtime(true) - BEFORE, 3) * 1000.0);
?>
<button type="button" class="otra--help-cursor dbg-bar--block" title="Elapsed time"
        tabindex="<?= $debugBarTabIndexActualValue++ ?>">
  🕑 <?= $elapsedTime ?> ms
</button>
<div class="dbg-bar--block--container">
  <p class="dbg-bar--block--container--element">
    Elapsed time since the entry point first line of code :
    <b><?= $elapsedTime ?> ms</b>
  </p>
</div>
