<?php
declare(strict_types=1);
$elapsedTime = round(microtime(true) - BEFORE, 3) * 1000;
?>
<button type="button" class="otra--help-cursor dbg-bar--block" title="Elapsed time">
  🕑 <?= $elapsedTime ?> ms
</button>
<div class="dbg-bar--block--container">
  <p class="dbg-bar--block--container--element">
    Elapsed time since the entry point first line of code :
    <b><?= $elapsedTime ?> ms</b>
  </p>
</div>
