<?php
declare(strict_types=1);
namespace otra\src\views\debugBar;
/**
 * @var int $debugBarTabIndexActualValue
 */
$logged = isset($_SESSION['sid']);
echo $logged
  ? '<button type="button" class="dbg-bar--block dbg-bar--logged otra--help-cursor" title="Is a user logged in?" tabindex="' .  $debugBarTabIndexActualValue++ . '">Connected</button>'
  : '<button type="button" class="dbg-bar--block dbg-bar--not-logged otra--help-cursor" title="Is a user logged in?" tabindex="' . $debugBarTabIndexActualValue++ . '">Disconnected</button>';
?>
<div class="dbg-bar--block--container">
  <p class="dbg-bar--block--container--element">
    The user is <b><?= $logged ? 'connected' : 'disconnected'?></b>
  </p>
</div>
