<?php
declare(strict_types=1);

use const otra\cache\php\{CORE_CSS_PATH, CORE_JS_PATH, CORE_VIEWS_PATH};
use function otra\src\views\debugBar\generateArrows;

require CORE_VIEWS_PATH . 'debugBar/macros.phtml';
$this::css([
  [CORE_CSS_PATH . 'partials/devMode/devMode'],
  [CORE_CSS_PATH . 'partials/devMode/devModePrint', true]
]);
generateArrows();
?>
<div id="dbg-bar" class="dbg-bar">
  <?php
  require CORE_VIEWS_PATH . 'debugBar/otra.phtml';
  require CORE_VIEWS_PATH . 'debugBar/php.phtml';
  require CORE_VIEWS_PATH . 'debugBar/route.phtml';
  require CORE_VIEWS_PATH . 'debugBar/http.phtml';
  require CORE_VIEWS_PATH . 'debugBar/chrono.phtml';
  require CORE_VIEWS_PATH . 'debugBar/cache.phtml';
  require CORE_VIEWS_PATH . 'debugBar/connection.phtml';
  require CORE_VIEWS_PATH . 'debugBar/templateMotor.phtml';
?>
  <button id="show-sql" class="dbg-bar--btn">Inspect SQL</button>
  <?php generateArrows('label') ?>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox');
