<?php
declare(strict_types=1);
namespace otra\src\views\debugBar;
use function otra\console\convertLongArrayToShort;
use const otra\cache\php\
{CACHE_PATH, CONSOLE_PATH, CORE_CSS_PATH, CORE_PATH, CORE_VIEWS_PATH};
use const otra\config\VERSION;

const
  DEBUG_BAR_PATH = CORE_VIEWS_PATH . 'debugBar/',
  CACHE_PHP_SESSION_PATH = CACHE_PATH . 'php/sessions/';

$sessionId = session_id();
define('ROUTE', urlencode($this->route));
define('SESSION_ID', $sessionId);
define('GET_PARAMETERS', '?route=' . ROUTE . '&session_id=' . SESSION_ID);

require CONSOLE_PATH . 'colors.php';
require CONSOLE_PATH . 'tools.php';
require DEBUG_BAR_PATH . 'macros.phtml';

if (!file_exists(CACHE_PHP_SESSION_PATH))
  mkdir(CACHE_PHP_SESSION_PATH);

$sessionDebugFile = CACHE_PHP_SESSION_PATH . sha1('ca' . $sessionId . VERSION . 'che') . '.php';

$responseHeaders = [];
$headers = headers_list();

foreach ($headers as $header)
{
  $header = explode(':', $header);
  $responseHeaders[array_shift($header)] = trim(implode(':', $header));
}

file_put_contents(
  $sessionDebugFile,
  '<?php declare(strict_types=1);namespace otra\cache\php\sessions;return ' .
convertLongArrayToShort([
  'GET' => $_GET,
  'POST' => $_POST,
  'COOKIE' => $_COOKIE,
  'SESSION' => $_SESSION,
  'requestHeaders' => apache_request_headers(),
  'responseHeaders' => $responseHeaders,
]) . ';' . PHP_EOL
);

if ($_SERVER['REMOTE_ADDR'] === '::1')
  chmod($sessionDebugFile, 0775);

$this::css([
  [CORE_CSS_PATH . 'partials/devMode/devMode'],
  [CORE_CSS_PATH . 'partials/devMode/devModePrint', true]
]);
generateArrows();
?>
<div id="dbg-bar" class="dbg-bar">
  <?php
  define(
    'SITE_HOST',
    (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']
  );
  $debugBarTabIndexActualValue = 950;

  foreach(['otra', 'php', 'route', 'http', 'chrono', 'cache', 'connection', 'templateStructure'] as $template)
  {
    require DEBUG_BAR_PATH . $template . '.phtml';
  }

  unset($template);
  require DEBUG_BAR_PATH . 'sass.phtml';
?>
  <a href="<?= SITE_HOST ?>/profiler/sql<?= GET_PARAMETERS ?>" rel="noopener nofollow noreferrer" target="profiler"
     class="dbg-bar--block" title="Check SQL logs" tabindex="<?= $debugBarTabIndexActualValue++ ?>">SQL</a>
  <?php generateArrows('label', $debugBarTabIndexActualValue) ?>
</div>
