<span class="otra--help-cursor dbg-bar--block" title="OTRA informations">OTRA <?= OTRA_VERSION ?></span>
<div class="dbg-bar--block--container">
  <p class="dbg-bar--block--container--element">
    Version : <b><?= OTRA_VERSION ?></b>
  </p>
  <p class="dbg-bar--block--container--element">
    Site : <a href="https://otra.tech" target="_blank" rel="nofollow noopener noreferrer">https://otra.tech</a>
  </p>
</div>
<span class="dbg-bar--primary dbg-bar--separator">|</span>
