<?php
$phpVersion = phpversion();
?>
<span class="otra--help-cursor dbg-bar--block" title="PHP informations">PHP <?= $phpVersion ?></span>
<div class="dbg-bar--block--container">
  <p class="dbg-bar--block--container--element">
    Version : <b><?= $phpVersion ?></b>
  </p>
  <p class="dbg-bar--block--container--element">
    Loaded Configuration File : <b><?= php_ini_loaded_file() ?></b>
  </p>
  <p class="dbg-bar--block--container--element">
    Modules : <?php
    $extensions = '';
    $extensionsArray = get_loaded_extensions();
    sort($extensionsArray);

    foreach ($extensionsArray as $phpExtension)
    {
      $extensions .= $phpExtension . ', ';
    }

    echo substr($extensions, 0, -2);
    ?>
  </p>
</div>
<span class="dbg-bar--primary dbg-bar--separator">|</span>
