<?php declare(strict_types=1);
/** @var $cacheEnabled */
if ($cacheEnabled)
{
  ?><button type="button" class="otra--help-cursor dbg-bar--block"
            title="⚠ This tool is not available with an enabled cache">⚠ Template structure</button>
  <div></div>
  <?php
} else
{ ?>
<button type="button" class="otra--help-cursor dbg-bar--block"
        title="Template structure as viewed by the template motor">Template structure</button>
  <div class="dbg-bar--block--container dbg-bar--block--container-motor-template">
    <?= $_SESSION['templateVisualization']; ?>
  </div>
<?php } ?>


