<?php
/** @var \src\MasterController $this */
$this::css(CORE_CSS_PATH . 'devMode'); ?>
<input type="radio" id="dbg--toggle--top" name="dbg--position" class="dbg--toggle-direction dbg--toggle-top" checked>
<input type="radio" id="dbg--toggle--right" name="dbg--position" class="dbg--toggle-direction dbg--toggle-right">
<input type="radio" id="dbg--toggle--bottom" name="dbg--position" class="dbg--toggle-direction dbg--toggle-bottom">
<input type="radio" id="dbg--toggle--left" name="dbg--position" class="dbg--toggle-direction dbg--toggle-left">
<div id="dbg-bar" class="dbg-bar">
   <?= '\'', $this->route, '\' | ', $this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s&nbsp;&nbsp;|&nbsp;&nbsp;<?php
  if (isset($_SESSION['sid']) === true) {
     ?><span class="dbg-on">Connected</span><?php
  } else {
    ?><span class="dbg-off">Disconnected</span><?php
  } ?> &nbsp;&nbsp;|&nbsp;&nbsp;<button id="show-sql" class="dbg-btn">Inspect SQL</button>
  <label for="dbg--toggle--top" class="dbg--toggle dbg--toggle-top">▲</label>
  <label for="dbg--toggle--right" class="dbg--toggle dbg--toggle-right">▶</label>
  <label for="dbg--toggle--bottom" class="dbg--toggle dbg--toggle-bottom">▼</label>
  <label for="dbg--toggle--left" class="dbg--toggle dbg--toggle-left">◀</label>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox'); ?>
