<?php
/** @var \src\MasterController $this */
$this::css(CORE_CSS_PATH . 'devMode'); ?>
<div id="dbg-bar" class="dbg-bar">
   <?= '\'', $this->route, '\' | ', $this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s&nbsp;&nbsp;|&nbsp;&nbsp;<?php
  if (isset($_SESSION['sid']) === true) {
     ?><span class="dbg-on">Connected</span><?php
  } else {
    ?><span class="dbg-off">Disconnected</span><?php
  } ?> &nbsp;&nbsp;|&nbsp;&nbsp;<button id="show-sql" class="dbg-btn">Inspect SQL</button>
    <p id="dbg--toggle" class="dbg--toggle">▶</p>
</div><div class="dbg-bar-xs dbg-hide">
	<p id="dbg--toggle-small" class="dbg--toggle-small">▼</p>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox'); ?>
