<?php
/** @var \src\MasterController $this */
$this::css(CORE_CSS_PATH . 'devMode'); ?>
<div id="dbg-bar" class="dbg-bar">
   <?= '\'', $this->route, '\' | ', $this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s&nbsp;&nbsp;|&nbsp;&nbsp;<span class="<?= (isset($_SESSION['sid'])) ? 'dbg-on' : 'dbg-off'?>">Connected</span>
    &nbsp;&nbsp;|&nbsp;&nbsp;<a id="show-sql" class="dbg-btn">Inspect SQL</a>
    <p id="dbg--toggle" class="dbg--toggle">▶</p>
</div><div class="dbg-bar-xs dbg-hide">
	<p id="dbg--toggle-small" class="dbg--toggle-small">▼</p>
</div>
<?php $this::js(CORE_JS_PATH . 'debug_bar');
  $this::js(CORE_JS_PATH . 'lightbox'); ?>
