<?php
declare(strict_types=1);

use const otra\cache\php\CORE_PATH;
use function otra\cache\php\{block,endblock};
// require_once because most of the time, blocks will be already used.
require_once CORE_PATH . 'templating/blocks.php' ?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width" />
<title>
<?php block('title'); ?>
Welcome to OTRA!
<?php endblock(); ?>
</title>

<!-- Favicons-->
<link href="/favicon.png" rel=apple-touch-icon sizes=16x16> <!-- 32x32 possible -->
<link rel="icon" type="image/png" href="favicon.png" />
<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->

<html lang="en">
<body>
<?php block('body'); ?>
Hello!
<?php endblock(); ?>
</body>
