<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>
  Exception!
</title>

<link rel="stylesheet" href="<?= '/src/resources/css/pages/otraException.css' ?>" />

<!-- Favicons-->
<link href="/favicon.png" rel=apple-touch-icon sizes=16x16> <!-- 32x32 possible -->
<link rel="icon" type="image/png" href="favicon.png" />

<html lang="en">
<body>
