<?
self::layout();
self::title('Welcome to the LPCMS !');
?>
<div id="backgroundspe"></div>
<div id="mainBgd"></div>
<div id="mainFrame">
<? require CMS_VIEWS_PATH . 'header.phtml'; ?>
  <div id="bgMiddle">

    <div class="moduleStyle1">
      <ul class="menusVHeaderUl nodecoration">
        <li class="menusVHeaderLi tcenter">
          Connexion
      </ul>
      <? $connCenter = true;require CMS_VIEWS_PATH . 'connection.phtml'; ?>
      <div class="clearBoth"></div>
      </div>
    </div>

  <?  require CMS_VIEWS_PATH . 'footer.phtml';  ?>
  </div>
</div>
