<ul id="menus">
  <li class="tab <? if ('Modules' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/modules"><a data-tooltip="Modules management">Modules</a>
  <li class="tab <? if ('General' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/general"><a data-tooltip="General options management">General options</a>
  <li class="tab <? if ('Stats' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/stats"><a data-tooltip="Statistics management">Stats</a>
  <li class="tab <? if ('Users' == $menu) echo 'activeTab '; ?> tcenter" data-href="/backend/users"><a data-tooltip="Users management">Users</a></ul>

<div id="content" class="fl"><? require __DIR__ . '/../ajax' . $menu; ?>
