<ul id="menus">
  <li class="tab <? if ('Modules' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/modules" data-tooltip="Modules management"><a>Modules</a>
  <li class="tab <? if ('General' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/general" data-tooltip="General options management"><a>General options</a>
  <li class="tab <? if ('Stats' == $menu) echo 'activeTab '; ?>tcenter" data-href="/backend/stats" data-tooltip="Statistics management"><a>Stats</a>
  <li class="tab <? if ('Users' == $menu) echo 'activeTab '; ?> tcenter" data-href="/backend/users" data-tooltip="Users management"><a>Users</a></ul>

<div id="content" class="fl"><? require __DIR__ . '/../ajax' . $menuFile; ?>
