<tabContent id="tab1">
	<div id="mainCfgDiv">
		<? $actualName = $cfg['name'];
		foreach($config as $cfg)
		{
			if($actualName != $cfg['name'])
			{
				$actualName = $cfg['name'];
				?> <div class="cfgSection"><?= $cfg['name'] ?></div>
				<?
			}
			?>
			<div class="cfgLine" data-id="<?= $cfg['id'] ?>">
				<label id="cfg_lab_<?= $cfg['id'] ?>"><?= $cfg['title'] ?></label>
				<?
				 switch($cfg['type'])
				 {
				 	case 0 :
				  ?>
				  	<input id="cfg_chk_<?= $cfg['id'] ?>" type="checkbox" class="noLabel" value="<?= $cfg['value'] ?>" />
				  	<label for="cfg_chk_<?= $cfg['id'] ?>"></label>
				  <? break;
				  case 1:
				  	?>
				  	<input type="number" class="input" value="<?= $cfg['value'] ?>"/>
				  	<?
				  	break;
				  case 2:
			  		?>
			  		<input class="input" value="<?= $cfg['value'] ?>"/>
			  		<?
				  } ?>
				  <a role="button" aria-labelledby="<? t('Edit this configuration line'); ?>" class="softBtn circleBorder edit _edit TTTL" data-tooltip="<? t('Edit this configuration line'); ?>"></a>
			</div>
		<? } ?>
	</div>
</tabContent>
