<tabContent id="tab1">
	<div id="main-cfg-div">
		<? $actualName = '';

		if(null !== $config)
		{
			foreach ($config as $cfg)
			{
				if ($actualName != $cfg['name'])
				{
					$actualName = $cfg['name'];
					?>
					<div class="cfg-section"><?= $cfg['name'] ?></div>
					<?
				}
				?>
				<div class="cfg-line" data-id="<?= $cfg['id'] ?>">
					<label id="cfg_lab_<?= $cfg['id'] ?>"><?= $cfg['title'] ?></label>
					<?
					switch ($cfg['type'])
					{
						case 0 :
							?>
							<input id="cfg_chk_<?= $cfg['id'] ?>" type="checkbox" class="no-label" value="<?= $cfg['value'] ?>"
										 placeholder="<?= $cfg['placeholder'] ?>"/>
							<label for="cfg_chk_<?= $cfg['id'] ?>"></label>
							<? break;
						case 1:
							?>
							<input type="number" class="input" value="<?= $cfg['value'] ?>" placeholder="<?= $cfg['placeholder'] ?>"/>
							<?
							break;
						case 2:
							?>
							<input class="input" value="<?= $cfg['value'] ?>" placeholder="<?= $cfg['placeholder'] ?>"/>
							<?
					} ?>
					<a role="button" aria-labelledby="<?= t('Edit this configuration line'); ?>"
						 class="soft-btn circle-border edit _edit tttl" data-tooltip="<?= t('Edit this configuration line'); ?>"></a>
				</div>
			<? }
		} ?>
	</div>
</tabContent>
