	<table id="table3">
		<thead id="usersHeader">
			<tr>
				<th></th>
				<th>Email</th>
				<th>Password</th>
				<th>Pseudo</th>
				<th>Role</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody id="usersBody">
			<tr>
				<td><input id="all" type="checkbox" data-tooltip="Select/Deselect All" /></td>
				<td><input class="search" /></td>
				<td></td>
				<td><input class="search" /></td>
				<td><input class="search" /></td>
			</tr>
			<? require ('search.phtml'); ?>
			<tr id="trOptions">
				<td colspan="6" class="options">
					<span id="prev" class="softBtn smallBtn fontBtn paging disabled" data-tooltip="Previous users">&laquo;</span>
					<span id="next" class="softBtn smallBtn fontBtn paging" data-tooltip="Next users">&raquo;</span>
					<span id="pageInd">Page <span id="currentPage">1</span> / <span id="lastPage"><?= ceil($count / $limit) ?></span> (<?= $count ?> users)</span>
					<div id="limit" class="select" data-last="<?= $user['id_user'] ?>" data-first="<?= $users[0]['id_user'] ?>">
			      <span class="fl input actualSelectValue">
			        <a data-value="3"><?= $limit ?></a>
			        <span class="fr selectArrow"></span>
			      </span>
			      <div class="clearBoth"></div>
			      <ul class="fl selectChoices">
			      	<li data-value="3" class="selectChoice">3
			      	<li data-value="6" class="selectChoice">6
			      	<li data-value="9" class="selectChoice">9
		      	</ul>
    			</div>
					<span id="add" class="fl softBtn smallBtn fontBtn" data-tooltip="Add a new user">+</span>
					<span id="delAll" class="fl softBtn" data-tooltip="Delete all the selected users !"></span>
					<span id="valAll" class="fl softBtn smallBtn" data-tooltip="Validate all the selected users !">V</span>
				</td>
			</tr>

			<tr><td class="final" colspan="6"></td></tr>
		</tbody>
	</table>
</div>

<? echo '<script> window.roles = window.roles || ' . json_encode($roles) . ';</script>';
