	<table id="table3" class="fl">
		<thead id="usersHeader">
			<tr>
				<th><input id="all" type="checkbox" data-tooltip="Select/Deselect All" /></th>
				<th>Email</th>
				<th>Password</th>
				<th>Pseudo</th>
				<th>Role</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody id="usersBody">
			<tr><td colspan="6"></td></tr>

			<? foreach($users as $user) {?>
			<tr id="<?= $user['id_user'] ?>">
				<td><input type="checkbox"/></td>
				<td class="mail"><?= $user['mail'] ?></td>
				<td><?= $user['pwd'] ?></td>
				<td><?= $user['pseudo'] ?></td>
				<td data-value="<?= $user['id_role'] ?>"><?= $user['nom'] ?></td>
				<td>
					<span class="softBtn edit" data-tooltip="Makes the line editable">Edit</span>
					<span class="softBtn delete" data-tooltip="Delete the user"></span>
				</td>
			</tr>
			<? } ?>
			<tr id="trOptions">
				<td colspan="6" class="options">
					<span id="prev" class="softBtn smallBtn fontBtn paging" data-tooltip="Previous users">&laquo;</span>
					<span id="next" class="softBtn smallBtn fontBtn paging" data-tooltip="Next users">&raquo;</span>
					<span id="pageInd">Page 1 / 1</span>
					<span id="add" class="fl softBtn smallBtn fontBtn" data-tooltip="Add a new user">+</span>
					<span id="delAll" class="fl softBtn" data-tooltip="Delete all the selected users !"></span>
					<span id="valAll" class="fl softBtn smallBtn" data-tooltip="Validate all the selected users !">V</span>
				</td>
			</tr>

			<tr><td class="final" colspan="6"></td></tr>
		</tbody>
	</table>
</div>

<? echo '<script> window.roles = window.roles || ' . json_encode($roles) . ';</script>';
