<?
 foreach($users as $user) {?>
  <tr id="<?= $user['id_user'] ?>">
    <td><input type="checkbox" role="checkbox" aria-checked="false"/></td>
    <td class="mail"><?= $user['mail'] ?></td>
    <td><?= $user['pwd'] ?></td>
    <td><?= $user['pseudo'] ?></td>
    <td data-value="<?= $user['id_role'] ?>"><?= $user['nom'] ?></td>
    <td>
      <span role="button" aria-labelledby="<? t('Edit the user'); ?>" class="softBtn circleBorder softBtnImage edit" data-action="edit" data-tooltip="<? t('Makes the line editable'); ?>"></span><!--
      --><span role="button" aria-labelledby="<? t('Delete the user'); ?>" class="softBtn circleBorder softBtnImage delete" data-action="delete" data-tooltip="Delete the user"></span>
    </td>
  </tr>
<? }
