<?
 foreach($users as $user) {?>
  <tr id="<?= $user['id_user'] ?>">
    <td>
      <input id="chk-<?= $user['id_user'] ?>" type="checkbox" role="checkbox" aria-checked="false" class="no-label" />
      <label for="chk-<?= $user['id_user'] ?>"></label>
    </td>
    <td class="mail"><?= $user['mail'] ?></td>
    <td>********</td>
    <td><?= $user['pseudo'] ?></td>
    <td data-value="<?= $user['fk_id_role'] ?>"><?= $user['nom'] ?></td>
    <td>
      <a role="button" aria-labelledby="<?= t('Edit the user'); ?>" class="soft-btn circle-border edit _edit tttl" data-tooltip="<?= t('Makes the line editable'); ?>"></a><!--
      --><a role="button" aria-labelledby="<?= t('Delete the user'); ?>" class="soft-btn circle-border delete _delete tttl" data-tooltip="Delete the user"></a>
    </td>
  </tr>
<? }
