<?php
declare(strict_types=1);
namespace otra\src\views\profiler\logs;

use const otra\cache\php\{BASE_PATH, DEV};
use function otra\src\views\profiler\showLogsFull;
?>
<div class="activatable-divs--item suffix" role="tabpanel">
  <a href="sql?route=<?= $_GET['route'] ?>" class="ripple ripple-link" rel="noopener noreferrer">SQL logs</a><br/><br/>
  <?php
  showLogsFull(
    'Trace',
    BASE_PATH . 'logs/' . DEV . '/trace.txt',
    'No trace logs.',
    ' open'
  );
  ?>
</div>
