<?php
declare(strict_types=1);
namespace otra\src\views\debugBar\routes;

use const otra\cache\php\CORE_VIEWS_PATH;
use function otra\cache\php\{block, endblock};

require CORE_VIEWS_PATH . 'profiler/layout.phtml';

block('title', 'Profiler — Logs');
block('view');

require CORE_VIEWS_PATH . 'profiler/macros.phtml';
?>
<div id="logs-container">
  <?php require CORE_VIEWS_PATH . 'profiler/logs/tabs.phtml'; ?>

  <div class="activatable-divs suffix">
    <?php
    require CORE_VIEWS_PATH . 'profiler/logs/development.phtml';
    require CORE_VIEWS_PATH . 'profiler/logs/production.phtml';
    ?>
  </div>
</div>
<?php endblock();
