<style>.oldLightbox{box-shadow: 0 0 3px #EEE, 0 0 4px 2px #222; padding: 1em;min-height:3em;max-width: 50em;top:40%;width:70%;}</style>
<!--[if lt IE 10]>
<div id="backgroundIE"></div>
<![endif]-->
<div class="lightboxContainer">
  <div class="lightbox oldLightbox tcenter">
    <div class="alignLeft">
      Ok, so you don't have the latest browser...<br />
      What if you make a little research in order to see if you can update you actual browser or just change to another browser ?<br />
      You'll see this site in a better way... Believe me ! Moreover, no client scripts support for IE8 and older browsers.
    </div>
  </div>
</div>
