<!DOCTYPE html><meta charset="utf-8"><meta name="viewport" content="width=device-width" /><title>
Profiler - SASS tree</title><!-- Favicons--><link href="/favicon.png" rel=apple-touch-icon sizes=16x16><!-- 32x32 possible --><link rel="icon" type="image/png" href="favicon.png" /><!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]--><html lang="en"><body><h1 class="otra-title">
  OTRA profiler - Data about the route
  <a href="http://https://dev.otra-framework.tech/helloworld" class="otra-title--link">HelloWorld</a></h1><div class="profiler-container flex-container"><ul class="vertical-menu vertical-menu--container"><li
    class="vertical-menu vertical-menu--container--item"><a
      href="http://https://dev.otra-framework.tech/profiler/logs?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="Logs">📄 </span><span class="vertical-menu--container--item--link--label">Logs</span></a></li><li
    class="vertical-menu vertical-menu--container--item"><a
      href="http://https://dev.otra-framework.tech/profiler/requests?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="Request / Response">🔃 </span><span class="vertical-menu--container--item--link--label">Request / Response</span></a></li><li
    class="vertical-menu vertical-menu--container--item"><a
      href="http://https://dev.otra-framework.tech/profiler/routes?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="Routes">📌 </span><span class="vertical-menu--container--item--link--label">Routes</span></a></li><li
    class="vertical-menu vertical-menu--container--item vertical-menu--container--item-active"><a
      href="http://https://dev.otra-framework.tech/profiler/css?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="SASS/SCSS analysis">🖌 </span><span class="vertical-menu--container--item--link--label">SASS/SCSS analysis</span></a></li><li
    class="vertical-menu vertical-menu--container--item"><a
      href="http://https://dev.otra-framework.tech/profiler/sql?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="SQL">🗃 </span><span class="vertical-menu--container--item--link--label">SQL</span></a></li><li
    class="vertical-menu vertical-menu--container--item"><a
      href="http://https://dev.otra-framework.tech/profiler/templateStructure?route=HelloWorld&session_id="
      rel="noreferrer noopener" class="vertical-menu--container--item--link" ><span title="Template structure">📄 </span><span class="vertical-menu--container--item--link--label">Template structure</span></a></li></ul><div class="sass-trees--container"><span class="sass-trees--container--error-message">There is no cache about SASS/SCSS files or there are no such files. To create the cache, launch : </span><pre class="sass-trees--container--error-message">otra genWatcher 0 1</pre><span class="sass-trees--container--error-message">and stops it when the file is generated.</span></div></div></body>
