<?php
use const otra\cache\php\TEST_PATH;
$title = 'Profiler — SASS tree';
$activeMenuItem = 'css';
require TEST_PATH . 'examples/profiler/partial.phtml'; ?> <div class=sass-trees--container> <span class=sass-trees--container--error-message>There is no cache about SASS/SCSS files or there are no such files. To create the cache, launch : </span> <pre class=sass-trees--container--error-message>otra genWatcher 0 1</pre> <span class=sass-trees--container--error-message>and stops it when the file is generated.</span></div> </div> </body><?= ' ' ?>
