<?php
use const otra\cache\php\TEST_PATH;
$title = 'Profiler — SQL';
$activeMenuItem = 'sql';
require TEST_PATH . 'examples/profiler/partial.phtml'; ?> <div id=sql-container> <div class=sql-buttons> <button type=button id=profiler--clear-sql-logs class="ripple sql-buttons--item">Clear SQL logs</button> <button type=button id=profiler--refresh-sql-logs class="ripple sql-buttons--item">Refresh SQL logs</button> </div> <div id=profiler--sql--logs class=profiler--sql--logs>No stored queries in /media/data/web/perso/otra/logs/dev/sql.txt.</div> </div> </div> </body><?= ' ' ?>
