<!DOCTYPE html><meta charset="utf-8"><meta name="viewport" content="width=device-width" /><title>
Profiler - SQL</title><!-- Favicons--><link href="/favicon.png" rel=apple-touch-icon sizes=16x16><!-- 32x32 possible --><link rel="icon" type="image/png" href="favicon.png" /><!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]--><html lang="en"><body><h1 class="otra-title">
  OTRA profiler - Data about the route
  <a href="http://https://dev.otra-framework.tech/helloworld">HelloWorld</a></h1><div class="profiler-container flex-container"><ul class="vertical-menu vertical-menu--container"><li
    class="vertical-menu vertical-menu--container--item"><a href="http://https://dev.otra-framework.tech/profiler/css?route=HelloWorld"
       rel="noreferrer noopener">SASS/SCSS analysis</a></li><li
    class="vertical-menu vertical-menu--container--item vertical-menu--container--item-active"><a href="http://https://dev.otra-framework.tech/profiler/sql?route=HelloWorld"
       rel="noreferrer noopener">SQL</a></li><li
    class="vertical-menu vertical-menu--container--item"><a href="http://https://dev.otra-framework.tech/profiler/templateStructure?route=HelloWorld"
       rel="noreferrer noopener">Template structure</a></li></ul></body><div id="sql-container"><div class="sql-buttons"><button type="button" id="profiler--clear-sql-logs" class="ripple sql-buttons--item">Clear SQL logs</button><button type="button" id="profiler--refresh-sql-logs" class="ripple sql-buttons--item">Refresh SQL logs</button></div><div id="profiler--sql--logs" class="profiler--sql--logs">No stored queries in /var/www/html/perso/otra/logs/dev/sql.txt.</div></div></div>
