<?php
declare(strict_types=1);
namespace otra\src\views\profiler\requests;
/** @var array $session Session that was logged in a file in `cache/php/sessions` folder */
?>
<div class="activatable-divs--item">
  <details class="accordion">
    <summary class="accordion">GET parameters</summary>
    <div class="accordion--block">
      <?php showParameters($session['GET'], 'GET parameters'); ?>
    </div>
  </details>

  <details class="accordion">
    <summary class="accordion">POST parameters</summary>
    <div class="accordion--block">
      <?php showParameters($session['POST'], 'POST parameters'); ?>
    </div>
  </details>

  <details class="accordion">
    <summary class="accordion">Request headers</summary>
    <div class="accordion--block">
      <?php showParameters($session['requestHeaders'], 'request headers'); ?>
    </div>
  </details>
</div>
