<?php
declare(strict_types=1);

use const otra\cache\php\{CORE_PATH, CORE_VIEWS_PATH};
use function otra\debugRouterError;
use function otra\cache\php\{block, endblock};

require CORE_VIEWS_PATH . '/layout.phtml';
block('title', '404 Not found !');
block('body');
?>
  <h1>Damn where is that page already?</h1>
  <div id="error">
    You're trying to access to : <?php
    // isset($_SERVER['HTTPS']) is necessary for an Apache setup
    $siteHost = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'];
    echo $siteHost . $_SERVER['REQUEST_URI']; ?>
    <br><br>
    <?php
    /** @var ?string $suggestedRoute */
    if ($suggestedRoute !== null) {
      ?>You can try to go to <a href="<?= $suggestedRoute ?>"><?= $suggestedRoute ?></a> instead.<?php
    } else {
      ?> Sorry, we don't have any relevant web pages for you right now.<?php
    }

    if ($_SERVER['REMOTE_ADDR'] === '127.0.0.1' || $_SERVER['REMOTE_ADDR'] === '::1')
    {
      ?> It does not work because the tested routes are :<br><br><?php
      require CORE_PATH . 'debugRouter.php';
      debugRouterError($_SERVER['REQUEST_URI']);
    }
    ?>
  </div>
<?php
endblock();
