<?php
declare(strict_types=1);
/**
 * @var string $message
 * @var string $code
 * @var string $file
 * @var int    $line
 * @var string $context
 * @var array  $backtraces
 */

require CORE_VIEWS_PATH . '/layout.phtml';
block('title', 'Exception !');
block('body');
?>
<div class="exception text-center">Exception</div>
<div class="explications text-center correct-display"><?php
  if (true === isset($code))
  	echo 'Error code <span class="exception-brown">', $code , '</span> in <span class="exception-file">' , $file , '</span> at line <span class="exception-line">' , $line, '</span><br />', $message;
  ?>
	<br />
	<table>
		<thead>
	  	<tr>
	  		<th>Error Code</th>
				<th>Function</th>
				<th>Line</th>
				<th>File</th>
				<th>Arguments</th>
			</tr>
		</thead>
		<tbody>
		  <?php
      for($i = 0, $trace = $backtraces, $max = count($trace); $i < $max; $i += 1)
		  {
		  	$now = $trace[$i];
		  	?><tr>
		  		<td></td>
		  	 	<td><?= (true === isset($now['function'])) ? $now['function'] : '-' ?></td>
				<td><?= (true === isset($now['line'])) ? $now['line'] : '-' ?></td>
        <td><?php if (true === isset($now['file']))
          {
            $traceFile = str_replace('\\', '/', $now['file']);
            echo (str_contains($traceFile, BASE_PATH)
              ? '<span title="' . $traceFile . '">' . substr($traceFile, strlen(BASE_PATH)) . '</span>'
              : $traceFile);
          } else
          {
            echo '-';
          }
        ?></td>
				<?php if (true === empty($now['args']))
				{ ?> <td></td></tr> <?php } else { ?>
				<td class="show-args">
						<em>Show</em>
				</td>
			</tr>
			<tr class="deep-content">
				<td colspan="5"><?php if(0 === $i) unset($now['args']['variables']);
          echo createShowableFromArray($now['args'], 'Arguments', 'variables');
        ?></td>
			</tr>
			<?php }
      } ?>
	  </tbody>
	</table>
	<br />
	<?= $context ?>
</div>
<?php endblock();
