<?
$this->layout();
self::title('Save our space - Accueil !');
?>
<!--[if (lt IE 10)]>
<style>
  body{ background: url(/images/bg.jpg)}

  #background-ie {
    /* background */
    background : #4b6c61; -ms-filter : "progid:DXImageTransform.Microsoft.Alpha(Opacity=75)";
    filter : alpha(opacity=75);
    opacity : 0.75;

    /* box */
    height : 100%; width : 100%;
    position : absolute;
    top : 0;
    z-index : -1
  }

  .old-lightbox {
    position : absolute;
    left : 15%
  }
</style>
<![endif]-->
<div class="main-bgd"></div>
<div class="background-spe"></div>
<div class="main-frame">
<? require CMS_VIEWS_PATH . 'header.phtml'; ?>
  <div class="bg-middle">
    <div>
      <? for ($i = 0; $i < 2; $i += 1)
      {
        echo '<div id="location' , $i , '">';
        if (empty($modules) === false)
        {
          foreach($modules[$i] as $type => $module) { require CMS_VIEWS_PATH . 'module.phtml'; } } ?>
        </div><?
      }?>
      <article class="article1" class="fl" role="main"><?= $article ?></article>
    </div>
  <div class="clear-both"></div>

  <? require CMS_VIEWS_PATH . 'footer.phtml';  ?>
  </div>
  <p class="design-by" class="center" data-tooltip="Main page">Designed by Péramo Lionel.</p>
</div>
