<?
$this->layout();
self::title('Save our space - Accueil !');
?>
<div id="backgroundspe"></div>
<div id="mainFrame">
<? require CMS_VIEWS_PATH . 'header.phtml'; ?>
  <div id="bgMiddle">
    <div>
      <? for($i=0; $i<2; $i += 1)
      {
        echo '<div id="location' , $i , '">';
        foreach($modules[$i] as $type => $module) { require CMS_VIEWS_PATH . 'module.phtml'; } ?>
        </div><?
      }?>
      <article id="article1" class="fl"><?= $article ?></article>
    </div>
  <div class="clearBoth"></div>

  <? require CMS_VIEWS_PATH . 'footer.phtml';  ?>
  </div>
  <p id="designby" class="center" data-tooltip="Main page">Designed by Péramo Lionel.</p>
</div>
