<?
$this->layout();
self::title('Save our space - Accueil !');
?>
<!--[if (lt IE 10)]>
<style>
  body{ background: url(/images/bg.jpg)}
  #backgroundIE{ background:#4B6C61;-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=75)";filter: alpha(opacity=75);opacity: 0.75; height:100%; position:absolute; top:0;width:100%; z-index:-1}
  .oldLightbox{position:absolute; left:15%}
</style>
<![endif]-->
<div id="container">
  <div id="mainBgd"></div>
  <div id="backgroundspe"></div>
  <div id="mainFrame">
  <? require CMS_VIEWS_PATH . 'header.phtml'; ?>
    <div id="bgMiddle">
      <div>
        <? for($i=0; $i<2; $i += 1)
        {
          echo '<div id="location' , $i , '">';
          if(!empty($modules))
          {
            foreach($modules[$i] as $type => $module) { require CMS_VIEWS_PATH . 'module.phtml'; } } ?>
          </div><?
        }?>
        <article id="article1" class="fl" role="main"><?= $article ?></article>
      </div>
    <div class="clearBoth"></div>

    <? require CMS_VIEWS_PATH . 'footer.phtml';  ?>
    </div>
    <p id="designby" class="center" data-tooltip="Main page">Designed by Péramo Lionel.</p>
  </div>
</div>
