<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name=viewport content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> Welcome to the LP Framework !</title>

<!--  Color of my app-->
<meta name="theme-color" content="#444">

<!-- Google SEO-->
<meta name=author content=https://plus.google.com/u/0/112398144630021094708?rel=author>
<meta name=description content="Erevent - Description d'Erevent">
<meta name=robots content="index,follow,noodp">
<meta name=googlebot content="index,follow">
<meta name=google content=notranslate>
<link rel=canonical href="https://dev.save-our-space.com/<?= substr($this->pattern,1); ?>">

<!--Apple mobile-->
<link href="/favicon.png" rel=apple-touch-icon sizes=16x16> <!-- 32x32 possible ->

<!-- IE Mobile-->
<meta name="application-name" content="Erevent - Description d'Erevent"/>
<meta name="msapplication-TileColor" content="#444"/>

<!-- Facebook Open Graph -->
<meta property="og:title" content="Besoin de développer une application web responsive de qualité ?">
<meta property="og:url" content="https://lionel-peramo.com/">
<meta property="og:site_name" content="Lionel Péramo - Besoin de développer une application web responsive de qualité ?">
<meta property="og:image" content="/images/my_photo.jpg">

<? self::favicon('favicon.png', 'favicon.ico'); ?>
<html>
<body>coucou</body>
