<?php require CORE_PATH . 'blocks.php' ?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name=viewport content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>
<?php block('title'); ?>
Welcome to OTRA!
<?php endBlock(); ?>
</title>

<!--  Color of my app-->
<meta name="theme-color" content="#444">

<!-- Google SEO-->
<meta name=author content=https://plus.google.com/u/0/112398144630021094708?rel=author>
<meta name=description content="OTRA - Homepage">
<meta name=robots content="index,follow,noodp">
<meta name=googlebot content="index,follow">
<meta name=google content=notranslate>

<!-- Favicons-->
<link href="/favicon.png" rel=apple-touch-icon sizes=16x16> <!-- 32x32 possible -->
<link rel="icon" type="image/png" href="favicon.png" />
<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->

<!-- IE Mobile-->
<meta name="application-name" content="OTRA - Homepage"/>
<meta name="msapplication-TileColor" content="#444"/>

<!-- Facebook Open Graph -->
<meta property="og:title" content="Want to develop faster websites ?">
<meta property="og:url" content="https://lionel-peramo.com/">
<meta property="og:site_name" content="OTRA - Want to develop faster websites ?">

<html lang="en">
<body>
<?php block('body'); ?>
Hello!
<!--  --><?php //block('body'); ?>
<!--  test-->
<!--  --><?php //endblock(); ?>
<?php endBlock(); ?>
</body>
