<? self::css(CORE_CSS_PATH . 'devMode'); ?>
<div id="dbg-bar" class="dbg-bar">
   <? echo '\'', $this->route, '\' | ', $this->bundle, '/', $this->module, '/', $this->controller, '/', $this->action,
   ' | ', round(microtime(true) - BEFORE, 3) ?>s | <span class="<?= (isset($_SESSION['sid'])) ? 'dbg-on' : 'dbg-off'?>">Connected</span>
   | <a id="show-sql" class="dbg-btn">Inspect SQL</a>
   <p id="toggle" class="toggle">▶</p>
</div><div class="dbg-bar-xs">
	<p id="toggle-small" class="toggle-small">▼</p>
</div>
<?php self::js(CORE_JS_PATH . 'debug_bar');
  self::js(CORE_JS_PATH . 'lightbox'); ?>
