<?
echo redText(PHP_EOL . 'PHP exception' . PHP_EOL . '=============' . PHP_EOL . PHP_EOL);

$typeWidth = 16; // the longest type is E_RECOVERABLE_ERROR
$functionWidth = 40;
$lineWidth = 4;
$fileWidth = 80;

if (isset($this->code)) echo 'Error type ' , cyanText($this->code), ' in ' , cyanText($this->file), ' at line ' , cyanText($this->line), PHP_EOL, $this->message, PHP_EOL;

/******************************
 * Write HEADERS of the table *
 ******************************/
echo PHP_EOL,
  lightBlueText(str_repeat('-', $typeWidth + $functionWidth + $lineWidth + $fileWidth + 80)), PHP_EOL,
  lightBlueText('|'), brown(), ' TYPE', str_repeat(' ', $typeWidth),
  lightBlueText('|'), brown(), ' Function', str_repeat(' ', $functionWidth),
  lightBlueText('|'), brown(), ' Line', str_repeat(' ', $lineWidth),
  lightBlueText('|'), brown(), ' File', str_repeat(' ', $fileWidth),
  lightBlueText('|'), brown(), ' Arguments', PHP_EOL,
  lightBlueText(str_repeat('-', $typeWidth + $functionWidth + $lineWidth + $fileWidth + 80)), endColor(), PHP_EOL;

/*******************************
 * Write the BODY of the table *
 *******************************/
for($i = 0, $trace = $backtraces, $max = count($trace); $i < $max; $i += 1)
{
  $now = $trace[$i];

  if(0 === $i) unset($now['args']['variables']);

  convertArrayToShowableConsole($now['args'], 'Arguments', 'variables');

  echo lightBlueText('| '), str_pad(0 === $i ? $this->code : '', $typeWidth + 4, ' '),
    /** FUNCTION */
    lightBlueText('|'),
    str_pad(isset($now['function'])
      ? ' ' . $now['function'] . ' '
      : ' -',
      $functionWidth + 9
    ),

    /** LINE */
    lightBlueText('|'),
    str_pad(isset($now['line'])
      ? ' ' . $now['line'] . ' '
      : ' -',
      $lineWidth + 5
    ),

    /** FILE
     *
     * The file path is shortened to the essential in order to leave more place for the path's end
     */
    lightBlueText('|'),
    str_pad(isset($now['file'])
      ? ' ' . substr($now['file'], strlen(BASE_PATH)) . ' '
      : ' -'
      , $fileWidth + 5
    ),

    /** ARGUMENTS */
    lightBlueText('|'),
    ' NOT IMPLEMENTED YET',

    PHP_EOL;

  // echo $now['args']; after args has been converted
}

echo lightBlueText(str_repeat('-', $typeWidth + $functionWidth + $lineWidth + $fileWidth + 80)), PHP_EOL;
// echo $this->context ...too big for console output !
