<?
self::layout();
self::title('Exception !');
?>
<div class="exception text-center">Exception</div>
<div class="explications text-center correct-display"><?
  if (true === isset($code))
  	echo 'Error code <span class="exception-brown">', $code , '</span> in <span class="exception-file">' , $file , '</span> at line <span class="exception-line">' , $line, '</span><br />', $message;
  ?>
	<br />
	<table>
		<thead>
	  	<tr>
	  		<th>Error Code</th>
				<th>Function</th>
				<th>Line</th>
				<th>File</th>
				<th>Arguments</th>
			</tr>
		</thead>
		<tbody>
		  <? for($i = 0, $trace = $backtraces, $max = count($trace); $i < $max; $i += 1)
		  {
		  	$now = $trace[$i];
		  	?><tr>
		  		<td></td>
		  	 	<td><?= (true === isset($now['function'])) ? $now['function'] : '-' ?></td>
				<td><?= (true === isset($now['line'])) ? $now['line'] : '-' ?></td>
				<td><?= (true === isset($now['file']))
					? (false !== strpos($now['file'], BASE_PATH)
						? substr($now['file'], strlen(BASE_PATH))
						: $now['file'])
					: '-'
				?></td>
				<? if (true === empty($now['args']))
				{ ?> <td></td></tr> <? } else { ?>
				<td class="show-args">
						<i>Show</i>
				</td>
			</tr>
			<tr class="deep-content">
				<td colspan="5"><? if(0 === $i) unset($now['args']['variables']);
				 convertArrayToShowable($now['args'], 'Arguments', 'variables'); echo $now['args']; ?></td>
			</tr>
			<? }
      } ?>
	  </tbody>
	</table>
	<br />
	<?= $context ?>
</div>
