<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>
<?php block('title'); ?>
Welcome to OTRA!
<?php endBlock(); ?>
</title>

<!-- Favicons-->
<link href="/favicon.png" rel=apple-touch-icon sizes=16x16> <!-- 32x32 possible -->
<link rel="icon" type="image/png" href="favicon.png" />
<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->

<html lang="en">
<body>
<?php block('body'); ?>
Hello!
<?php endBlock(); ?>
</body>
